### ISSUE TITLE
handle-change assumes an :input target inside the event

### ISSUE THREAD

**Issue by stevebuik** [luciodale/fork#12]
I want to use the react rc-slider component with Fork. That means calling the Fork handle-change fn from that slider. 

Unfortunately handle-change reads the name and value by assuming a change event from a dom input. 
rc-slider creates no inputs at all so it breaks. I tried creating a synthetic event but that got messy quickly.

Based on the "pillars" in the readme, I hope you might be willing to accept a PR allowing an override of the fns used inside handle-change (or some alternative solution)

Opening this issue to start the discussion. In the meantime I'll play with a fix in a fork.

**Comment by luciodale** [comment]
What I ended up doing with components like that is to use the `set-values` function. You can pass down to your rc-slider and do something like:

```clojure
{:onChange (fn [slider-vals] (set-values {"rc-slider" slider-vals}))
```

You might find this way more convenient and straight forward, but feel free to propose a useful change :)

**Comment by stevebuik** [comment]
Ah, I didn't see this in your Bulma impls. Thanks!

Yes, it would be good to explain this in the README
