### ISSUE TITLE
Support for server/remote calls without a submit

### ISSUE THREAD

**Issue by stevebuik** [luciodale/fork#13]
I want my form to send to server without a submit i.e. whenever valid changes are made. what’s your advice on how to do this? Currently I just fire a re-frame event in the validation fn but that seems a bit of an impure hack.

Idea: pass the up to date errors and touched to the send-server-request fn?

**Comment by luciodale** [comment]
I added `:errors`, `:touched`, and `:dirty` args to the custom function passed to `send-server-request` in v2.0.4. :)

P.S. Never dispatch events during the rendering phase. Always link events to user-generated actions such as click events and so on to avoid very nasty bugs :)
