### ISSUE TITLE
path as a vector for use with assoc-in etc

### ISSUE THREAD

**Issue by Ramblurr** [luciodale/fork#16]
Fork is a great little library, I'm using it a lot in a web app that has lots of little independent form widgets.

One thing that sort of nags at me is that the path is a top-level key into the app db. I've arranged my app db in a hierarchical structure such that independent parts are self-contained under their own key in app db, but all the form widgets now are polluting the top level of the db

It would be pretty great if `path` could also be a vector and instead was accessed with the `*-in` functions.

**Comment by luciodale** [comment]
I'll add this is today :) Sensible change thanks for suggesting

**Comment by luciodale** [comment]
v2.1.5 only accepts a vector as path value, so one can do either `[:one-key]` or `[:k1 :k2 :k3]`. In other words, a single keyword as value is no longer supported.

**Comment by Ramblurr** [comment]
thanks for getting to this so quickly!

So this is a breaking change? I'd add a big notice to the changelog, this will probably require users to change their apps.

**Comment by luciodale** [comment]
Yeah, It is in fact. I added the info to the changelog and updated all examples in the readme.. hopefully it won't be too annoying :)
