### ISSUE TITLE
Multi Select drop down not working as expected

### ISSUE THREAD

**Issue by wkok** [luciodale/fork#19]
When I create a multi select drop down:

```
[:select {:name "roles"
              :value (values "roles" [:viewer])
              :on-change handle-change
              :on-blur handle-blur
              :multiple true}
      [:option {:value :viewer} "Viewer"]
      [:option {:value :editor} "Editor"]]
```

It renders correctly:
![image](https://user-images.githubusercontent.com/5214136/93795402-3ae67400-fc31-11ea-8ec1-21c7ac1063ab.png)

However, one cannot select any other value, all options loses their selected state.

Am I doing something incorrectly? Do you perhaps have an example for a multi select?

Note that for a single select drop down, it works perfectly.

**Comment by luciodale** [comment]
Hey! The multi-select dropdown is a bit different. You need to do some custom logic:

```clojure
[fork/form {:initial-values {"status" []}}
   (fn [{:keys [set-handle-change handle-blur values]}]
     [:form
      [:select
       {:multiple true
        :name "status"
        :value (values "status")
        :on-change #(set-handle-change
                     {:value (let [opts (array-seq (-> % .-target .-options))]
                               (keep (fn [x] (when (.-selected x)
                                               (.-value x))) opts))
                      :path ["status"]})
        :on-blur handle-blur}
       [:option {:value "married"}
        "Married"]
       [:option {:value "single"}
        "Single"]
       [:option {:value "pns"}
        "Prefer Not To Say"]]])]
```

For this to work smoothly, bump to `v2.2.2`, or if you don't want to change dependency, you have to return a non-lazy sequence inside the `:value` key of `set-handle-change` i.e. `(doall (keep...))`

**Comment by wkok** [comment]
Thank you for the example!

Unfortunately I still struggle to get it to work. I've copied your code exactly, ran it in my project with Fork version `v2.2.2` & my original `v2.1.0`, also tried with `(doall (keep...))` & without `doall` but in all cases get the following error when selecting one of the options:

views.cljs:125 Uncaught TypeError: **Cannot read property 'cljs$core$IFn$_invoke$arity$1' of null**
    at eval (views.cljs:125)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackImpl (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:307)
    at executeDispatch (react-dom.development.js:390)
    at executeDispatchesAndReleaseTopLevel (react-dom.development.js:415)
    at forEachAccumulated (react-dom.development.js:3260)
    at runEventsInBatch (react-dom.development.js:3305)
    at handleTopLevel (react-dom.development.js:3515)


Does it maybe depend on a specific version of reagent? I'm using v0.10.0

**Comment by wkok** [comment]
Apologies, please ignore my previous (now deleted) comment, I did nor refresh my fork dependency version properly.

Got it to work now, from using your example, thank you!

**Comment by luciodale** [comment]
Happy it's working now! :D
