### ISSUE TITLE
set-handle-change

### ISSUE THREAD

**Issue by schpaa** [luciodale/fork#22]
Can you please explain what this is for and how to use it?

I am trying to insert my own value in the handle-change of a date-field inside a field-array but have no idea how to do this...

```
:handle-change #(let [t (-> % .-target .-value)
                      custom-value (date/field-date->date t)]
                   (log/info custom-value)
                   ; now where/how to store my custom-value?
...
```

**Comment by luciodale** [comment]
Hello!
`set-handle-change` takes a map argument with the following keys:
`:path` -> being a relative path that is used to assoc the new value. The path is relative to the `:values` map in the state.
`:value` -> being the new value to you want to set. 

```clojure
(set-handle-change
 {:value "Joe" ;; or (fn [previous-val] "Joe")
  :path ["name"]})
```

If you want to use it in a field-array context, the path should be specified like this:
`[field-array-name idx input-key]`, which translates into:

```clojure
(set-handle-change 
 {:path [:users 3 :name]
  :value (date/field-date->date t)})
```

Of course I am assuming that your field-array top key is `:users`, the idx of the field-array group you're changing is `3`, and the input name is `:name`. The only dynamic value in the path should be the `idx` that you can pass down from your map-indexed loop.

Hope it's clear enough :)
