### ISSUE TITLE
Explicit value path being changed 

### ISSUE THREAD

**Issue by lowecg** [luciodale/fork#24]
Hello,

I'm seeing some unexpected behaviour when I specify my own value path.

Part of the path is based on a UUID, generated as follows:

`certificate-id` is generated elsewhere using `(str (random-uuid))`

The path I'm attempting to use is:

` [:certifications k-certificate-id :description]`

Where `k-certificate-id` is the result of `(keyword certificate-id)`.

```
(let [{:keys [values, set-handle-change]} form-props
        k-certificate-id (keyword certificate-id)]

   (println ":certifications" (:certifications values))
   (println "keyword certificate-id" k-certificate-id)
   (println "certificate-id" certificate-id)
   (println "DESCRIPTION" (get-in values [:certifications k-certificate-id :description]))

   [text-field {:id         (str "certificate-description-" certificate-id)
                :value      (get-in values [:certifications k-certificate-id :description])
                :on-change  #(set-handle-change
                               {:value (event-value %)
                                :path  [:certifications k-certificate-id :description]})}]
```

Entering data into this field doesn't take. That usually points to the setting and getting of the field value not being aligned.

The output from the print statement confirms this:

```
:certifications {:cdf-53254-ed-484e-91-b-3cf-4fd-03dc-7d-6e-0 {:description d}}
keyword certificate-id :cdf53254-ed48-4e91-b3cf-4fd03dc7d6e0
certificate-id cdf53254-ed48-4e91-b3cf-4fd03dc7d6e0
DESCRIPTION nil
```

The key in `:certifications` is my UUID but reformatted to this:

`:cdf-53254-ed-484e-91-b-3cf-4fd-03dc-7d-6e-0`

This morphing of the key seems to be what's causing the issue.

What's weirder is if I adapt the `on-change` to report the result of calling `set-handle-change`, then output is what I would expect:
```
:on-change  (fn [e]
                                 (let [params {:value (event-value e)
                                               :path  [:certifications k-certificate-id :description]}
                                       result (set-handle-change params)]
                                   (println "SET-HANDLE-CHANGE RESULT" (get-in result [:values :certifications]))
                                   result))
```
Outputs:
```
SET-HANDLE-CHANGE RESULT {:cdf53254-ed48-4e91-b3cf-4fd03dc7d6e0 {:description d}}
:certifications {:cdf-53254-ed-484e-91-b-3cf-4fd-03dc-7d-6e-0 {:description d}}
keyword certificate-id :cdf53254-ed48-4e91-b3cf-4fd03dc7d6e0
certificate-id cdf53254-ed48-4e91-b3cf-4fd03dc7d6e0
```

The outer form is specified as:

```
             [fork/form {:path              [:form :list-products]
                         :keywordize-keys   true
                         :prevent-default?  true
                         :clean-on-unmount? true
                         :initial-values    draft-product
                         :on-submit         #(rf/dispatch [:app.list-products.events/submit-list-product %])
                         }
              (fn [{:keys [on-submit-server-message
                           form-id
                           handle-submit] :as form-props}]

```

I have previously used this approach successfully with an integer value rather than the UUID. But I really could do with the UUID working in this case.

Any ideas on what's changing the path? I'm using fork version 2.4.1.

**Comment by luciodale** [comment]
Hey there! I can't reproduce your problem. I set up this small example and it all works as expected:

```clojure
[fork/form {}
   (fn [{:keys [set-handle-change values]}]
     (let [k-certificate-id :cdf-53254-ed-484e-91-b-3cf-4fd-03dc-7d-6e-0]
       [:div
        (with-out-str (pprint/pprint values))
        [:br]
        [:input
         {:value (get-in values [:certifications k-certificate-id :description])
          :on-change #(set-handle-change {:value (-> % .-target .-value)
                                          :path  [:certifications k-certificate-id :description]})}]]))]
```

The `get-in` bit successfully retrieves the value. Anyways, I'd just use the UUID string for `k-certificate-id` without casting it to a keyword. That looks better to me. If you can provide a small reproducible example I can explore on this more :)

**Comment by luciodale** [comment]
Also, note that in your example the UUIDs of the print statements are different:

```clojure 
:cdf-53254-ed-484e-91-b-3cf-4fd-03dc-7d-6e-0 != :cdf53254-ed48-4e91-b3cf-4fd03dc7d6e0
```

It looks like there's some code that reruns somewhere and your UUID gets changed. Can't really tell without more context but it seems the problem should be this. :)

**Comment by lowecg** [comment]
Thank you for the minimal example.

I ran it outside of my existing form, and it worked perfectly.

I'm using material UI and the form properties are passed through to a function that is wrapped with [make-styles](https://github.com/arttuka/reagent-material-ui/blob/d968e4e8658a67020f2d80985611b5809ce88eb9/src/core/reagent_material_ui/styles.cljs#L20).

It's supposed to add CSS styles to a function's parameters by adding ":classes" to existing panel props.

Before referencing a panel, the UUID is fine. Pass the form props to the panel, and I can see the corruption.

**Comment by luciodale** [comment]
mmm, still not sure... I think it's not something related to material UI or fork. I believe it might be due to the way some logic is handled at the component level. Can you share a gist for me to look at?

**Comment by lowecg** [comment]
Morning Lucio

I've put together a minimal app demonstrating the issue:

https://github.com/lowecg/issue-data-corruption

Run it using `npm run watch`

Let me know if you need anything else.

Cheers,

Chris.

**Comment by luciodale** [comment]
Hey Chris,

I've been pretty busy lately.. Will soon have chance to look at this ;)

**Comment by lowecg** [comment]
Hi Lucio,

I am using a workaround to this, so no rush. In case anyone else is getting stung by this, the details of workaround are as follows:

Instead of using map values directly where the form panel is referenced, supply map values via a fn:
```
;; not working as per OP (supplying props directly)
[certification {:form-props     form-props
                        :certificate-id certificate-id}]

;; where the panel is defined like so:
(defn panel [{:keys [classes, certificate-id, form-props, test-props]}]
;; ...
)
 
(def ^:private with-custom-styles (styles/with-styles custom-styles))

(def certification (with-custom-styles panel))
```

Wrap the function props in a fn:
```
;; working
[certification {:get-props (fn [] {:form-props     form-props
                                                      :certificate-id certificate-id})}]

;; where the panel is defined like so:
(defn panel [{:keys [classes, get-props]}]
  (let [{:keys [certificate-id, form-props, test-props]} (get-props)]
    ;; ...
))
 
(def ^:private with-custom-styles (styles/with-styles custom-styles))

(def certification (with-custom-styles panel))
```

Cheers,

Chris
