### ISSUE TITLE
Reset "dirty" state after submit

### ISSUE THREAD

**Issue by lowecg** [luciodale/fork#25]
Hi,

Is there a way to remove dirty state from a form?

My form's initial values are populated using data retrieved from a DB. Once I have successfully saved my form's edits via a submit, I'd like to remove the dirty state from the form since the form state is now consistent with the DB.

I'm using the dirty state to drive "you have unsaved changes" type logic which currently persists after saving.

I've looked at `set-untouched` and `reset` but they do not have the desired effect. For example, I'm using something like this:

```
(rf/reg-event-fx
  ::submit-entity
  (fn [{:keys [db]} [_ {:keys [values, path, reset]}]]
      (make-server-call {:values values
                            :on-update (fn [item]
                                         (reset {:values values}))})

      {:db (-> db
               (fork/set-submitting path true))
       })))
```

This has no apparent effect on the dirty state.

Dirty state seems to be a comparison between initial-values and current values. So I'm feeling like I'm barking up the wrong tree.

Any suggestions?

**Comment by luciodale** [comment]
Hi!

In your reset call I believe you can simply add `{:initial-values values :values values}`. This should fix your issue.

**Comment by luciodale** [comment]
Thanks for the repo! v2.4.2 for the fix ;)
