### ISSUE TITLE
 Fork should set all fields to touched on submission

### ISSUE THREAD

**Issue by DrBuchkov** [luciodale/fork#44]
From my understanding, the correct behavior is to set to touched on submission so you can then display and error/validation messages. Formik does the same https://formik.org/docs/guides/form-submission

**Comment by luciodale** [comment]
Yeah, the point was to not enforce any initial values.. if you're using `touched` exposed by the API you shouldn't have any problems, but if you're reaching for the `touched` key directly in your state you have to replicate what I'm doing [here.](https://github.com/luciodale/fork/blob/master/src/fork/core.cljs#L14-L17)
