### ISSUE TITLE
Custom submit handlers should have access to the reset handler

### ISSUE THREAD

**Issue by psagers** [luciodale/fork#7]
I'm attempting to implement the following straightforward workflow with re-frame and fork:

1. Load an entity from the server into the app-db (via REST, GraphQL, etc.).
2. Present a form with initial values set to the entity's current values.
3. On submit, post modified values to the server.
4. On success, receive the updated entity and install it into the app-db.
5. Reset the form, deriving a new set of initial values from the updated entity.

Your basic multiple-submit AJAX form. This very nearly works: the only hitch is that the submit handler has a very limited view of the fork map, which does not include the reset handler. Is this just an oversight? Are the contents of the on-submit argument carefully chosen, or just what seemed useful at the time?

At a glance, it seems like it should be easy to thread through. I'm happy to prepare a pull request if that's helpful.

Thanks

**Comment by luciodale** [comment]
Originally, the `on-submit` arguments contained mostly all fork helpers. In later releases I reduced the number of helpers to make it clearer and more concise. Having said this, I am happy to reintroduce those helpers for which there are valid use cases, and I think that `reset` should definitely be there, so thanks for pointing it out. You can go ahead with a pull request :)
