### ISSUE TITLE
:clean-on-unmount? broken or vestigial

### ISSUE THREAD

**Issue by psagers** [luciodale/fork#9]
The :clean-on-unmount? option under re-frame ends up dispatching the :fork.re-frame/clean event, which is not registered. It looks like the option may be obsolete, although some app-db cleanup may still be warranted.

Thanks

**Comment by luciodale** [comment]
Besides the fact that the on clean event doesn’t exist anymore, I was thinking about whether we should still support the `component-will-unmount` Lifecycle method, as react deprecated it in favour of useEffect.

**Comment by luciodale** [comment]
I removed `clean-on-unmount?` in v2.0.1, as react doesn't support `component-will-unmount` anymore.

**Comment by psagers** [comment]
Out of curiosity, could you link to a reference to React dropping support for componentWillUnmount? I see that they've [deprecated](https://reactjs.org/blog/2019/08/08/react-v16.9.0.html) [componentWillMount](https://reactjs.org/docs/react-component.html#mounting), but I can't find any references to deprecating [componentWillUnmount](https://reactjs.org/docs/react-component.html#unmounting).

Thanks

**Comment by luciodale** [comment]
Oh my! It's not deprecated, you are right! I shouldn't work when I am too tired :) I'll revert.

**Comment by luciodale** [comment]
If you pull v2.0.2 it should work properly now. Let me know :)
